documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]

cicd:
  - changed-files:
      - any-glob-to-any-file: [".github/**"]

salesforce:
  - changed-files:
      - any-glob-to-any-file: ["force-app/**"]
