name: Salesforce Smart Deployment

on:
  workflow_dispatch:
    inputs:

      deploymentType:
        description: "Deployment Type"
        required: true
        type: choice
        options:
          - SpecificPR
          - LatestMergeToMain

      prNumber:
        description: "PR Number"
        required: false

      targetEnvironment:
        description: "Target Org"
        required: true
        type: choice
        options:
          - DEV
          - SP
          - POD3

      testLevel:
        description: "Test Level"
        required: true
        type: choice
        options:
          - RunLocalTests
          - RunSpecifiedTests
          - RunAllTestsInOrg
          - NoTestRun


permissions:
  contents: read
  pull-requests: read


jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Validate PR
        if: github.event.inputs.deploymentType == 'SpecificPR'

        run: |

          if [ -z "${{ github.event.inputs.prNumber }}" ]
          then

              echo "PR number required"

              exit 1

          fi


  deploy:

    runs-on: ubuntu-latest

    needs: validate

    environment:
      name: ${{ github.event.inputs.targetEnvironment }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Install CLI + GitHub CLI
        run: |

          npm install @salesforce/cli --global

          sudo apt-get update

          sudo apt-get install gh -y

          sf --version
          gh --version


      - name: Install Delta Plugin
        run: |

          yes | sf plugins install sfdx-git-delta


      - name: Authenticate

        run: |

          TARGET="${{ github.event.inputs.targetEnvironment }}"

          if [ "$TARGET" = "DEV" ]
          then
             echo "${{ secrets.DEV_ENVIRONMENT_SEC }}" > auth.txt

          elif [ "$TARGET" = "SP" ]
          then
             echo "${{ secrets.SP_ENVIRONMENT_SEC }}" > auth.txt

          else
             echo "${{ secrets.POD3_ENVIRONMENT_SEC }}" > auth.txt
          fi

          sf org login sfdx-url \
          --sfdx-url-file auth.txt \
          --alias TARGETORG

          rm auth.txt


      - name: Generate Delta

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |

          mkdir -p delta-package

          if [ "${{ github.event.inputs.deploymentType }}" = "SpecificPR" ]
          then

              PR="${{ github.event.inputs.prNumber }}"

              BASE=$(gh pr view $PR --json baseRefOid --jq '.baseRefOid')

              HEAD=$(gh pr view $PR --json headRefOid --jq '.headRefOid')

          else

              PR=$(gh pr list \
              --state merged \
              --limit 1 \
              --json number \
              --jq '.[0].number')

              BASE=$(gh pr view $PR --json baseRefOid --jq '.baseRefOid')

              HEAD=$(gh pr view $PR --json headRefOid --jq '.headRefOid')

          fi


          sf sgd source delta \
          --from "$BASE" \
          --to "$HEAD" \
          --output-dir delta-package \
          --source-dir force-app \
          --generate-delta


      - name: Preview

        run: |

          find delta-package || true


      - name: Deploy

        run: |

          if [ ! -d "delta-package/force-app" ]
          then

              echo "No deployable files"

              exit 0

          fi


          FILES=$(find delta-package/force-app -type f | wc -l)

          echo "Detected files:$FILES"


          if [ "$FILES" -eq 0 ]
          then

              echo "No metadata found"

              exit 0

          fi


          sf project deploy start \
          --source-dir delta-package/force-app \
          --target-org TARGETORG \
          --test-level ${{ github.event.inputs.testLevel }} \
          --ignore-conflicts \
          --wait 30
