name: Selective Test Validation

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  validate-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global

      - name: Detect Changed Files
        run: |
          git fetch

          git diff --name-only HEAD~1 HEAD > changed.txt

          cat changed.txt

      - name: Validate Apex Changes
        run: |
          if grep -q "\.cls$" changed.txt
          then
            echo "Apex class changes detected"
          else
            echo "No Apex changes"
          fi
